### ISSUE TITLE
Thug Python 3.8 support

### ISSUE THREAD

**Issue by geeksailor** [REMnux/salt-states#265]
Devs / @digitalsleuth ,
Wanted to give you the heads up that as of Oct 9 Thug dropped support for Python 3.8. Since Ubuntu 20.04 defaults to Python 3.8, this may break the tool. Unless upgrading to 3.9 is possible for the Remnux suite without breaking other tools. Otherwise you may need to set the salt to install version 5.7 which was an update on Sep 25th to keep the tool working with this suite.
Cheers!

**Comment by digitalsleuth** [comment]
This shouldn't be too much of an issue, as we have a thug Docker for REMnux, which we can update to the most recent version of thug and use Python 3.9. It'll likely be the best course of action anyways to use the docker, since 20.04 is an LTS version and will be supported until 2025.

I'll see about updating the docker, and using it in the environment for the future. Otherwise, we could move it to a venv as well with Python 3.9.

Thanks for the heads up on this!

**Comment by geeksailor** [comment]
Awesome. Figured it was probably an easy fix. Glad you already have something kind of in place to accommodate this kind of thing.
Cheers!

**Comment by digitalsleuth** [comment]
@geeksailor , thanks for the heads up, I'll track that as well!

**Comment by lennyzeltser** [comment]
Newly issued release I just issued release v2024.1.4 to include this change includes the thug, qiling, speakeasy, and nth changes.

**Comment by geeksailor** [comment]
@lennyzeltser Thank you for the update! If this is patched than I will close this thread.
